version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    versioning-strategy: increase-if-necessary
    commit-message:
      prefix: "Composer"
      include: "scope"
    schedule:
      interval: "weekly"
