name: run-pint-larastan

on:
  pull_request:
    branches: ["main"]

jobs:
  pint-larastan:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Cache Composer Dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run Laravel Pint (Lint Check)
        run: composer format -- --test

      - name: Run Larastan Analysis
        run: composer analyse
